name: escdiary
description: "Escape Room Diary - Personal escape room game record keeper"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # State Management
  provider: ^6.1.2

  # Local Storage
  sqflite: ^2.4.0
  sqflite_common_ffi_web: ^0.4.0
  path: ^1.9.0
  shared_preferences: ^2.5.3

  # Utilities
  uuid: ^4.5.1
  intl: ^0.20.2
  firebase_core: ^4.2.1
  firebase_analytics: ^12.0.4
  upgrader: ^12.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
